services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_DB: oa
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
